project:
  type: website

website:
  title: "xy = lambda"
  navbar:
    right:
      - about.qmd
      - icon: linkedin
        text: LinkedIn
        href: https://www.linkedin.com/in/alejandro-pérez-sanjuán/
      - icon: github
        text: Github
        href: https://github.com/Xylambda

format:
  html:
    theme: cosmo
    css: styles.css

notebooks:
  execute: true
